export const STARTACTION='STARTACTION';
export const SUCCESSACTION='SUCCESSACTION';
export const ERRORACTION='ERRORACTION';
export const ADDLISTACTION='ADDLISTACTION';
export const DEFAULTACTION='DEFAULTACTION';