export const STARTALARM='STARTALARM';
export const SUCCESSALARM='SUCCESSALARM';
export const ERRORALARM='ERRORALARM';
export const ADDALARM='ADDALARM';
export const ADDLISTALARM='ADDLISTALARM';
export const DELETEALARM='DELETEALARM';
export const EDITALARM='EDITALARM';
export const DEFAULTALARM = 'DEFAULTALARM';