export const STARTDEVICEROOM='STARTDEVICEROOM';
export const SUCCESSDEVICEROOM='SUCCESSDEVICEROOM';
export const ERRORDEVICEROOM='ERRORDEVICEROOM';
export const ADDDEVICEROOM='ADDDEVICEROOM';
export const ADDLISTDEVICEROOM='ADDLISTDEVICEROOM';
export const DELETEDEVICEROOM='DELETEDEVICEROOM';
export const EDITDEVICEROOM='EDITDEVICEROOM';
export const DEFAULTDEVICEROOM='DEFAULTDEVICEROOM';