export const STARTDEVICEINFO='STARTDEVICEINFO';
export const SUCCESSDEVICEINFO='SUCCESSDEVICEINFO';
export const ERRORDEVICEINFO='ERRORDEVICEINFO';
export const ADDDEVICEINFO='ADDDEVICEINFO';
export const ADDLISTDEVICEINFO='ADDLISTDEVICEINFO';
export const DELETEDEVICEINFO='DELETEDEVICEINFO';
export const EDITDEVICEINFO='EDITDEVICEINFO';
export const DEFAULTDEVICEINFO='DEFAULTDEVICEINFO';