export const STARTDEVICE='STARTDEVICE';
export const SUCCESSDEVICE='SUCCESSDEVICE';
export const ERRORDEVICE='ERRORDEVICE';
export const ADDDEVICE='ADDDEVICE';
export const ADDLISTDEVICE='ADDLISTDEVICE';
export const DELETEDEVICE='DELETEDEVICE';
export const EDITDEVICE='EDITDEVICE';
export const DEFAULTDEVICE = 'DEFAULTDEVICE';