export const STARTHISTORY='STARTHISTORY';
export const SUCCESSHISTORY='SUCCESSHISTORY';
export const ERRORHISTORY='ERRORHISTORY';
export const ADDHISTORY='ADDHISTORY';
export const ADDLISTHISTORIES='ADDLISTHISTORIES';
export const DELETEHISTORY='DELETEHISTORY';
export const EDITHISTORY='EDITHISTORY';